version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: wordpress-gest-mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: g3st
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.3.1-php7.3-apache
    container_name: wordpress-gest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    volumes:
      - .wordpress/data:/var/www/html

  ftp:
    # optionally replace username/repo:tag with your name and image details
    image: stilliard/pure-ftpd:latest
    container_name: wordpress-gest-ftp
    restart: always
    environment:
      PUBLICHOST: 192.168.178.47
      FTP_USER_NAME: "admin"
      FTP_USER_PASS: "admin"
      FTP_USER_HOME: "/var/www/html"
      FTP_USER_UID: 33
      FTP_USER_GID: 33
    volumes:
      - .wordpress/data:/var/www/html
      - .wordpress/ssl:/etc/ssl/private
    ports:
      - target: 21
        published: 21
        protocol: tcp
        mode: host

    # Bind each passive ports to the host
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
        
volumes:
  db_data: {}
